name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    name: Rust ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.92.0
          - stable

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt --check
      - run: cargo test
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo rustdoc -- -D missing-docs
      - run: cargo package --no-verify
